### ISSUE TITLE
Non 16:9 monitors

### ISSUE THREAD

**Issue by TheMegaTB** [lupoDharkael/flameshot#7]
Okay, so it might be an issue regarding both ultrawide monitors (speaking of 2.35:1) **and** multiple displays.
When taking a screenshot on such setups it basically creates a misplaced overlay across the screen which contains the correct content but is offset by some value.
![img-2017-07-03-213452](https://user-images.githubusercontent.com/5037967/27805872-7c3528d2-6037-11e7-99da-512c2cfd16df.png)
On the left used to be another chrome window (right edge still visible) but instead the overlay which is supposed to be centered is offset to the left. Again I don't know if it is a bug related to multiple monitors or to ultrawides since I don't have another monitor hooked up currently but it might still mess things up since my xorg config includes some variables regarding it.

**Comment by lupoDharkael** [comment]
I'm unable to test with multiple monitors right now but I'll try to do it as soon as I can.
I'll create a new branch of experimental support for hidpi and multi-monitor configurations.
This requires a lot of investigation/testing because this kind of changes could break actual working configurations.

**Comment by lupoDharkael** [comment]
https://github.com/lupoDharkael/flameshot/issues/2#issuecomment-314707988

**Comment by lupoDharkael** [comment]
it should be fixed if you test it from the master branch. Please tell me if it works with your hardware.

**Comment by TheMegaTB** [comment]
I just tested the master branch (specifically commit 07e1df1c50ef796b8c7a67519fd0212d74445c9a ) and the result still matches the above image. Some more context:
- i3wm
- ArchLinux
- 21:9 Monitor (3440x1440)

One thing I just noticed in `arandr`:
![img-2017-07-13-191310](https://user-images.githubusercontent.com/5037967/28178589-54eb5132-67ff-11e7-9dab-587af467a889.png)
There is some padding to the left of my screen (basically its position is at X = 1920) due to the (currently not connected) second monitor. That might be causing the issue since the shift of the screenshot roughly matches the padding.

**Comment by lupoDharkael** [comment]
The screen grab seems to work ok now. The problem seems that your system has some kind of virtual screen and it's being grabbed within the physical screen. The problem is that Flameshot sets the grabbed screen starting from the first physical monitor in the the coord (0, 0). This can be fixed analysing the offsets of the screens. I need to find hot to recreate something like this in order to start testing a solution.

**Comment by Martin-Eckleben** [comment]
This is why I started to get involved in Flameshot.
The oldest issue btw. :)
As I right now tried to reproduce it for a photo It does not happen anymore.

I'll definitely look into this!

**Comment by Martin-Eckleben** [comment]
No ARandR padding for me.

![image](https://user-images.githubusercontent.com/1571683/92311484-b1d80780-efb7-11ea-99ab-a33c08db6318.png)

**Comment by borgmanJeremy** [comment]
I am fairly sure this is related to fractional scaling. I have been digging into it.

**Comment by EchoGroot** [comment]
我也遇到了，截屏时整个屏幕往左平移了

**Comment by EchoGroot** [comment]
> 我也遇到了，截屏时整个屏幕往左平移了

找到原因了，屏幕缩放之前是1.25，就有问题。还原到1.0就正常了

**Comment by skewty** [comment]
I have a 1920x1200 monitor (left of main, portrait mode) and a 2560x1600 monitor (main display).  Both are not scaled.  Flameshot only shows overlay on the leftmost display.  The issue doesn't seem to have anything to do with fractional scaling.

This system is running Fedora 33 Wayland session.

**Comment by borgmanJeremy** [comment]
@skewty can you try building from source on the master branch? I recently merged something to help with wayland.

**Comment by skewty** [comment]
> @skewty can you try building from source on the master branch? I recently merged something to help with wayland.

@borgmanJeremy 
Done.  The current code in master does not have the overlay issue I reported above / fixes my issue.  Thanks!

This is big enough to warrant a new tagged release, is it not?

**Comment by borgmanJeremy** [comment]
Yeah im looking to release 0.9 soon-ish. I was really pushing to have upload plugins done for 0.9 but its going to juit have to push out I think.

**Comment by skewty** [comment]
I'd like to suggest a small improvement to overlay "help boxes" positioning.  They should position themselves on the "primary" display (in Gnome) (I am assuming KDE has similar), not the leftmost display.

**Comment by HnHareJin** [comment]
I have a similar issue, it seems like a QT HiDPI problem. I’m not sure if it’s the same problem, but the following command worked great for me. 
```shell
QT_AUTO_SCREEN_SCALE_FACTOR=0 flameshot
```
I can finally take a screenshot, lol

**Comment by C0rn3j** [comment]
`flameshot 0.9.0-1`

![image](https://user-images.githubusercontent.com/1641362/115971953-e64f0280-a54b-11eb-8cc6-77275488c642.png)

Still have the issue on Arch Linux, on KDE, with Nvidia driver.

**Comment by edio** [comment]
I can confirm this issue.

It is only reproducible under 2 conditions:
1. multiple displays
2. Global scale factor in KDE's kscreen is > 100%

I dumped environment of flameshot from 2 runs (with 100% and 150% scaling), and this is the diff
```
[~]$ diff /home/dmytroko/flameshot.envbad.txt /home/dmytroko/flameshot.envok.txt  
4c4
< SESSION_MANAGER=local/****:@/tmp/.ICE-unix/2252667,unix/****:/tmp/.ICE-unix/2252667
---
> SESSION_MANAGER=local/****:@/tmp/.ICE-unix/2249766,unix/****:/tmp/.ICE-unix/2249766
19c19
< QT_SCREEN_SCALE_FACTORS=eDP1=1.5;DP1=1.5;DP2=1.5;HDMI1=1.5;HDMI2=1.5;VIRTUAL1=1.5;
---
> QT_SCREEN_SCALE_FACTORS=eDP1=1;DP1=1;DP2=1;HDMI1=1;HDMI2=1;VIRTUAL1=1;
34c34
< XDG_SESSION_ID=7
---
> XDG_SESSION_ID=5
45c45
< XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session2
---
> XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1
```
Based on this I made an assumption, that flameshot incorrecty handles the `QT_SCREEN_SCALE_FACTORS` variables.

Observed case 1
1. Set global scale to 100% 
2. Log out and Log in
3. flameshot works ok

Observed case 2
1. Repeat steps from case 1
2. Set global scale to 150%
3. Restart plasma and window manager (`kquitapp5 plasmashell && kstart5 plasmashell &`) and all the necessary apps to pick up new settings
4. flameshot works ok

Observed case 3
1. Repeat steps form case 2
2. Restart flameshot
3. flameshot works ok (I'm confused at this point)

Observed case 4
1. Set global scale to 150%
2. Log out and Log in
3. flameshot does not work

Observed case 5
1. Repeat steps of case 4
2. Restart flameshot with 
  ```
  export QT_SCREEN_SCALE_FACTORS="eDP1=1;DP1=1;DP2=1;HDMI1=1;HDMI2=1;VIRTUAL1=1;"
  flameshot gui
  ```
3. flameshot does not work (I'm confused again)

I hope this helps. If any additional info/experiments are needed, please let me know, I'm willing to help with whatever to make this fixed.

**Comment by Starrah** [comment]
I'm affected by this bug too. Hopes it could be fixed.

**Comment by sctse999** [comment]
This issue still exists in Kubuntu 23.10. I have two monitors, one with the laptop running 2880 x 1800 and another external monitor running 3840 x 2160, both are scaled at 150%. The whole screen displaced to the left when taking screen capture. Any solution?

**Comment by sctse999** [comment]
Update:

This has been solved by adding the following parameter to start flameshot

```/bin/sh -c 'env QT_SCREEN_SCALE_FACTORS="1" /usr/bin/flameshot gui -p ~/Pictures'```

**Comment by avindra** [comment]
Still having this issue. `QT_SCREEN_SCALE_FACTORS=1` doesn't help

**Comment by avindra** [comment]
Ah, setting `QT_SCALE_FACTOR=1` works for me.

**Comment by linuxtyp** [comment]
Hello. I tried both settings and got some pretty intresting results:
Im running Linux Mint 21.3 Cinnamon.
When run in tmux both commands worked.
```
❯ /bin/sh -c 'env QT_SCREEN_SCALE_FACTORS="1" /usr/bin/flameshot gui' 
flameshot: info: Screenshot aborted.                                                          │
❯ /bin/sh -c 'env QT_SCALE_FACTOR="1" /usr/bin/flameshot gui'
```
Now i wanted to add it to my custom shortcut
![image](https://github.com/flameshot-org/flameshot/assets/85036211/b7ad9d0d-f0ef-4217-b65b-20843a423a7e)
But when pressing print i get the same offset as usual. The offset i get is 5 centimeter black space on the bottom on every one of the 3 monitors.
![image](https://github.com/flameshot-org/flameshot/assets/85036211/17153b44-afc3-4928-8137-16f8040dd2fa)
I tried a new approch:
gnome-terminal -- /bin/sh -c 'env QT_SCALE_FACTOR="1" /usr/bin/flameshot gui'
Worked in the terminal, but again not with shortcut.
Would appreciate any tipps, love flameshot but this issue is really annoying.

**Comment by Faaaabian** [comment]
Hello y'all,

I am also experiencing this issue with flameshot (on ArchLinux, KDE Plasma) and tested around a little bit.
If the top left corner is on a screen like in the following configuration, everyting works as expected.

![image](https://github.com/user-attachments/assets/1e6f8761-1ffa-48bd-b683-cbeeba50b360)

If the top left corner happens not to be on a screen, like in this scenario (which is my current setup) flameshot spawns on my main monitor (the bigger one) with a black border on top and the content of the left screen below.

![image](https://github.com/user-attachments/assets/e7db53b7-7e1e-4432-9591-593e11a7a7c9)

I also tested starting flameshot from the terminal to get some error output and at least for my setup, this theory appears plausible to me:

![image](https://github.com/user-attachments/assets/693db2cd-df22-41d6-a534-a2482f7ba1be)

For now I will probably just move my lefthand monitor upwards. I would appreciate any tips because I really loved flameshot but on this new installation it just doesn't want to work.

**Comment by mmahmoudian** [comment]
This should have been fixed with #4498 
If you can, try compiling from the master branch and let us know is this issue still persists. I'm going to close this for now, but if the issue persists, we will re-open it.
